version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5000" # Change 5000 to 5001 (or any other available port)
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET_KEY=your-secret-key
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
